title: Dennis Kim, CFA
logo: /profile_elements/pfp1.jpg
description: Fascinated by the way people interact with objects, their environment, and others
# show_downloads: true
theme: jekyll-theme-minimal
